# Generated by Django 3.0.7 on 2020-07-29 07:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source_incident_id', models.TextField(verbose_name='source incident ID')),
                ('details_url', models.TextField(blank=True, validators=[django.core.validators.URLValidator], verbose_name='details URL')),
                ('description', models.TextField(blank=True)),
                ('ticket_url', models.TextField(blank=True, help_text='URL to existing ticket in a ticketing system.', validators=[django.core.validators.URLValidator], verbose_name='ticket URL')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IncidentRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParentObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('parentobject_id', models.TextField(verbose_name='parent object ID')),
                ('url', models.TextField(blank=True, validators=[django.core.validators.URLValidator], verbose_name='URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceSystemType',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActiveIncident',
            fields=[
                ('incident', models.OneToOneField(help_text='Whether the incident has been resolved.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='active_state', serialize=False, to='argus_incident.Incident')),
            ],
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='argus_incident.SourceSystemType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_system', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('object_id', models.TextField(blank=True, verbose_name='object ID')),
                ('url', models.TextField(validators=[django.core.validators.URLValidator], verbose_name='URL')),
                ('source_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_set', to='argus_incident.SourceSystem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='argus_incident.ObjectType')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('incident1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='argus_incident.Incident')),
                ('incident2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='argus_incident.Incident')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_relations', to='argus_incident.IncidentRelationType')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='object',
            field=models.ForeignKey(help_text='The most specific object that the incident is about.', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='argus_incident.Object'),
        ),
        migrations.AddField(
            model_name='incident',
            name='parent_object',
            field=models.ForeignKey(blank=True, help_text='An object that the above `object` is possibly a part of.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='argus_incident.ParentObject'),
        ),
        migrations.AddField(
            model_name='incident',
            name='problem_type',
            field=models.ForeignKey(help_text='The type of problem that the incident is about.', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='argus_incident.ProblemType'),
        ),
        migrations.AddField(
            model_name='incident',
            name='source',
            field=models.ForeignKey(help_text='The source system that the incident originated in.', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='argus_incident.SourceSystem'),
        ),
        migrations.AddConstraint(
            model_name='sourcesystem',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='sourcesystem_unique_name_per_type'),
        ),
        migrations.AddConstraint(
            model_name='object',
            constraint=models.UniqueConstraint(fields=('object_id', 'source_system'), name='object_unique_object_id_per_source_system'),
        ),
        migrations.AddConstraint(
            model_name='object',
            constraint=models.UniqueConstraint(fields=('name', 'type', 'source_system'), name='object_unique_name_and_type_per_source_system'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(fields=('source_incident_id', 'source'), name='incident_unique_source_incident_id_per_source'),
        ),
    ]
