# Generated by Django 3.0.7 on 2020-08-03 10:58

import argus.incident.models
from django.db import migrations, models


def set_all_names_lowercase(apps, schema_editor):
    SourceSystemType = apps.get_model("argus_incident", "SourceSystemType")

    non_lowercase_source_types = []
    for source_type in SourceSystemType.objects.all():
        name = source_type.name
        if not name.islower():
            non_lowercase_source_types.append(source_type)
            SourceSystemType.objects.get_or_create(name=name.lower())

    for source_type in non_lowercase_source_types:
        source_type.instances.update(type=source_type.name.lower())
        source_type.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesystemtype',
            name='name',
            field=models.TextField(primary_key=True, serialize=False, validators=[argus.incident.models.validate_lowercase]),
        ),
        migrations.RunPython(set_all_names_lowercase, migrations.RunPython.noop),
    ]
