# Generated by Django 3.0.10 on 2020-11-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incident',
            name='incident_unique_source_incident_id_per_source',
        ),
        migrations.AlterField(
            model_name='incident',
            name='source_incident_id',
            field=models.TextField(blank=True, default='', verbose_name='source incident ID'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(condition=models.Q(source_incident_id__gt=''), fields=('source_incident_id', 'source'), name='incident_unique_source_incident_id_per_source'),
        ),
    ]
