# Generated by Django 5.2 on 2025-06-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("argus_incident", "0001_squashed_incident_20250514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.TextField(
                choices=[
                    ("STA", "Incident start"),
                    ("END", "Incident end"),
                    ("CHI", "Incident change"),
                    ("RES", "Incident restart"),
                    ("CLO", "Close"),
                    ("REO", "Reopen"),
                    ("ACK", "Acknowledge"),
                    ("OTH", "Other"),
                    ("LES", "Stateless"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="incidenttagrelation",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
