# Generated by Django 5.2.7 on 2026-02-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0001_squashed_incident_20250514'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesystem',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
