# Generated by Django 3.2 on 2021-04-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0002_empty_source_incident_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
