# Generated by Django 3.0.7 on 2020-08-03 12:57

import argus.incident.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0002_sourcesystemtype_lowercase_validator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-start_time']},
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='timestamp',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='incident',
            name='start_time',
            field=models.DateTimeField(help_text='The time the incident was created.'),
        ),
        migrations.AddField(
            model_name='incident',
            name='end_time',
            field=argus.incident.fields.DateTimeInfinityField(blank=True, help_text="The time the incident was resolved or closed. If not set, the incident has no state; if 'infinity' is checked, the incident has state, but has not yet been resolved or closed.", null=True),
        ),
    ]
