# Generated by Django 5.2.13 on 2026-06-22 12:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0002_sourcesystem_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesystem',
            name='heartbeat_frequency',
            field=models.DurationField(blank=True, help_text="Expected to send heartbeat at least every N seconds. Lower bound: 60 seconds. Upper bound: 1 day. Valid inputs: seconds (as an integer, e.g. 86400), DD HH:MM:SS (1 00:00:00), ISO 8601 periods (P1D, note the T is needed if less than a day), PostgreSQL's day-time interval format (1 day)", null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60)), django.core.validators.MaxValueValidator(datetime.timedelta(days=1))]),
        ),
    ]
