# Generated by Django 5.2.13 on 2026-06-15 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0002_sourcesystem_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesystem',
            name='heartbeat_frequency',
            field=models.IntegerField(blank=True, help_text='Expected to send heartbeat at least every N seconds, lower bound: 60 seconds', null=True, validators=[django.core.validators.MinValueValidator(60)]),
        ),
    ]
