# Generated by Django 3.0.7 on 2020-08-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0003_start_time_end_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveIncident',
        ),
    ]
