# Generated by Django 5.2.11 on 2026-06-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("argus_incident", "0003_sourcesystem_heartbeat_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.TextField(
                choices=[
                    ("STA", "Incident start"),
                    ("END", "Incident end"),
                    ("CHI", "Incident change"),
                    ("RES", "Incident restart"),
                    ("CLO", "Close"),
                    ("REO", "Reopen"),
                    ("ACK", "Acknowledge"),
                    ("OTH", "Other"),
                    ("LES", "Stateless"),
                ]
            ),
        ),
    ]
