# Generated by Django 3.0.7 on 2020-08-09 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('argus_incident', '0005_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentTagRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags_added', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_tag_relations', to='argus_incident.Incident')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_tag_relations', to='argus_incident.Tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='incidenttagrelation',
            constraint=models.UniqueConstraint(fields=('tag', 'incident'), name='incidenttagrelation_unique_tags_per_incident'),
        ),
    ]
