# Generated by Django 3.2.11 on 2022-03-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0006_incident_search_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.TextField(choices=[('STA', 'Incident start'), ('END', 'Incident end'), ('CHI', 'Incident change'), ('CLO', 'Close'), ('REO', 'Reopen'), ('ACK', 'Acknowledge'), ('OTH', 'Other'), ('LES', 'Stateless')]),
        ),
    ]
