# Generated by Django 4.2.11 on 2024-04-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("argus_incident", "0007_alter_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
