# Generated by Django 3.0.7 on 2020-08-11 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_start_events(apps, schema_editor):
    Incident = apps.get_model("argus_incident", "Incident")
    Event = apps.get_model("argus_incident", "Event")

    for incident in Incident.objects.all():
        Event.objects.create(
            incident=incident,
            actor=incident.source.user,
            timestamp=incident.start_time,
            type="STA",
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('argus_incident', '0007_delete_objecttype_object_parentobject_problemtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(choices=[('STA', 'Incident start'), ('END', 'Incident end'), ('CLO', 'Close'), ('REO', 'Reopen'), ('ACK', 'Acknowledge'), ('OTH', 'Other')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caused_events', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='argus_incident.Incident')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RunPython(create_start_events, migrations.RunPython.noop),
    ]
