# Generated by Django 3.0.7 on 2020-08-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0008_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='ack', serialize=False, to='argus_incident.Event')),
            ],
            options={
                'ordering': ['-event__timestamp'],
            },
        ),
    ]
