# Generated by Django 3.0.8 on 2020-08-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0009_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesystem',
            name='base_url',
            field=models.TextField(blank=True, help_text="Base url to combine with an incident's relative url to point to more info in the source system."),
        ),
    ]
