# Generated by Django 3.0.7 on 2020-08-14 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('argus_incident', '0010_sourcesystem_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='source',
            field=models.ForeignKey(help_text='The source system that the incident originated in.', on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='argus_incident.SourceSystem'),
        ),
        migrations.AlterField(
            model_name='incidentrelation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_relations', to='argus_incident.IncidentRelationType'),
        ),
        migrations.AlterField(
            model_name='sourcesystem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='argus_incident.SourceSystemType'),
        ),
        migrations.AlterField(
            model_name='sourcesystem',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='source_system', to=settings.AUTH_USER_MODEL),
        ),
    ]
