# Generated by Django 3.0.8 on 2020-08-19 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0011_incident_and_sourcesystem_foreign_keys_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='received',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 8, 49, 4, 903813, tzinfo=utc)),
        ),
    ]
