# Generated by Django 3.0.8 on 2020-09-03 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0012_event_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='received',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
