# Generated by Django 3.0.8 on 2020-09-03 08:08

import argus.incident.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_incident', '0013_noop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='key',
            field=models.TextField(validators=[argus.incident.validators.validate_key]),
        ),
    ]
