# All available variables are described in documentation
# https://megalinter.io/configuration/

LINTER_RULES_PATH: .

ENABLE_LINTERS:
  - PYTHON_BLACK
  - PYTHON_FLAKE8

# Make workflow fail even on non blocking errors
FORMATTERS_DISABLE_ERRORS: false

PYTHON_BLACK_CONFIG_FILE: pyproject.toml
PYTHON_FLAKE8_CONFIG_FILE: tox.ini

PYTHON_FLAKE8_ARGUMENTS: --select=E9,F63,F7,F82
