coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%

ignore:
  - "manage.py"
  - "setup.py"
  - "tests/**"
  - "src/argus/site/settings/**"
  - "src/argus/spa/dataporten/social.py"
  - "**/apps.py"
  - "**/wsgi.py"
  - "**/test*.py"
  - "**/*test.py"
  - "**/migrations/**"
