# Generated by Django 2.2.5 on 2019-09-30 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSystemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(blank=True, max_length=20, verbose_name='subject ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(verbose_name='URL')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='alert.SubjectType')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='alert.NetworkSystemType')),
            ],
        ),
        migrations.CreateModel(
            name='AlertQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.IntegerField(verbose_name='alert ID')),
                ('on_maintenance', models.BooleanField()),
                ('event_history_url', models.URLField(blank=True, verbose_name='event history URL')),
                ('netbox_history_url', models.URLField(blank=True, verbose_name='netbox history URL')),
                ('event_details_url', models.URLField(blank=True, verbose_name='event details URL')),
                ('value', models.IntegerField()),
                ('severity', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('device', models.IntegerField(blank=True, null=True)),
                ('netbox', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_qs', to='alert.EventType')),
                ('network_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_qs', to='alert.NetworkSystem')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_qs', to='alert.Subject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_qs', to='alert.AlertType')),
            ],
            options={
                'ordering': ['-timestamp'],
                'default_related_name': 'alert_qs',
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.IntegerField(verbose_name='alert ID')),
                ('on_maintenance', models.BooleanField()),
                ('event_history_url', models.URLField(blank=True, verbose_name='event history URL')),
                ('netbox_history_url', models.URLField(blank=True, verbose_name='netbox history URL')),
                ('event_details_url', models.URLField(blank=True, verbose_name='event details URL')),
                ('value', models.IntegerField()),
                ('severity', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('device', models.IntegerField(blank=True, null=True)),
                ('netbox', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_hists', to='alert.EventType')),
                ('network_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_hists', to='alert.NetworkSystem')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_hists', to='alert.Subject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_hists', to='alert.AlertType')),
            ],
            options={
                'verbose_name_plural': 'alert histories',
                'ordering': ['-start_time'],
                'default_related_name': 'alert_hists',
            },
        ),
    ]
