# Generated by Django 2.2.5 on 2019-11-21 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('alert_id', models.CharField(max_length=20, verbose_name='alert ID')),
                ('details_url', models.URLField(blank=True, verbose_name='details URL')),
                ('description', models.TextField(blank=True)),
                ('ticket_url', models.URLField(blank=True, help_text='URL to existing ticket in a ticketing system.', verbose_name='ticket URL')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('NAV', 'NAV'), ('Zabbix', 'Zabbix')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParentObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('parentobject_id', models.CharField(max_length=20, verbose_name='parent object ID')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActiveAlert',
            fields=[
                ('alert', models.OneToOneField(help_text="Whether the alert's problem has been resolved.", on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='active_state', serialize=False, to='alert.Alert')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=20, verbose_name='object ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('network_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_objects', to='alert.NetworkSystem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='alert.ObjectType')),
            ],
        ),
        migrations.AddConstraint(
            model_name='networksystem',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_name_per_type'),
        ),
        migrations.AddField(
            model_name='alertrelation',
            name='alert1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alert.Alert'),
        ),
        migrations.AddField(
            model_name='alertrelation',
            name='alert2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alert.Alert'),
        ),
        migrations.AddField(
            model_name='alertrelation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_relations', to='alert.AlertRelationType'),
        ),
        migrations.AddField(
            model_name='alert',
            name='object',
            field=models.ForeignKey(help_text='The most specific object that the alert was about.', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alert.Object'),
        ),
        migrations.AddField(
            model_name='alert',
            name='parent_object',
            field=models.ForeignKey(blank=True, help_text='An object that the above `object` is possibly a part of.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alert.ParentObject'),
        ),
        migrations.AddField(
            model_name='alert',
            name='problem_type',
            field=models.ForeignKey(help_text='The type of problem that the alert is informing about.', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alert.ProblemType'),
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.ForeignKey(help_text='The network management system that the alert came from.', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alert.NetworkSystem'),
        ),
        migrations.AddConstraint(
            model_name='object',
            constraint=models.UniqueConstraint(fields=('object_id', 'network_system'), name='unique_object_id_per_network_system'),
        ),
        migrations.AddConstraint(
            model_name='object',
            constraint=models.UniqueConstraint(fields=('name', 'type', 'network_system'), name='unique_name_and_type_per_network_system'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('alert_id', 'source'), name='unique_alert_id_per_source'),
        ),
    ]
