# Generated by Django 2.2.5 on 2019-10-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentobject',
            name='parentobject_id',
            field=models.CharField(max_length=20, verbose_name='parent object ID'),
        ),
        migrations.AlterField(
            model_name='parentobject',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
