# Generated by Django 2.2.5 on 2019-10-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_start', models.DateTimeField()),
                ('interval_stop', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='parentobject',
            name='parentobject_id',
            field=models.CharField(max_length=20, verbose_name='parent object ID'),
        ),
        migrations.AlterField(
            model_name='parentobject',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
