# Generated by Django 2.2.5 on 2019-10-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_parentobject_alter_blank_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='network_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_objects', to='alert.NetworkSystem'),
        ),
    ]
