# Generated by Django 2.2.5 on 2019-10-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_notification_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_profile',
            name='interval_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='notification_profile',
            name='interval_stop',
            field=models.TimeField(),
        ),
    ]
