# Generated by Django 2.2.5 on 2019-10-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_auto_20191018_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_profile',
            name='interval_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification_profile',
            name='interval_stop',
            field=models.DateTimeField(),
        ),
    ]
