# Generated by Django 2.2.5 on 2019-10-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_alert_ticket_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('alert1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alert.Alert')),
                ('alert2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alert.Alert')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_relations', to='alert.AlertRelationType')),
            ],
        ),
    ]
