# Generated by Django 2.2.5 on 2019-10-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_auto_20191018_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_profile',
            name='name',
            field=models.CharField(default='tjalveprofilen', max_length=40),
            preserve_default=False,
        ),
    ]
