# Generated by Django 2.2.5 on 2019-11-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_alertrelation_alertrelationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveAlert',
            fields=[
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='active_state', serialize=False, to='alert.Alert')),
            ],
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp']},
        ),
    ]
