# Generated by Django 2.2.5 on 2019-11-20 12:22

from django.db import migrations, models


def change_network_system_type_from_fk_to_char(apps, schema_editor):
    NetworkSystem = apps.get_model('alert', 'NetworkSystem')
    NetworkSystemType = apps.get_model('alert', 'NetworkSystemType')

    for network_system in NetworkSystem.objects.all():
        system_type = NetworkSystemType.objects.get(pk=int(network_system.type))
        type_name = system_type.name.upper()
        type_key = 'NAV' if type_name == 'NAV' else 'Zabbix'
        network_system.type = type_key
        network_system.save()


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_active_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networksystem',
            name='type',
            field=models.CharField(choices=[('NAV', 'NAV'), ('Zabbix', 'Zabbix')], max_length=6),
        ),
        migrations.RunPython(change_network_system_type_from_fk_to_char, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='NetworkSystemType',
        ),
    ]
