# Generated by Django 2.2.5 on 2019-11-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_delete_networksystemtype_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='networksystem',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_name_per_type'),
        ),
    ]
