# Generated by Django 5.2.3 on 2025-11-21 13:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("argus_notificationprofile", "0001_squashed_notificationprofile_20250512"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedMaintenanceTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(
                            9999,
                            12,
                            31,
                            22,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        ),
                        null=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "filters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="planned_maintenance_tasks",
                        to="argus_notificationprofile.filter",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_maintenance_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="end_time_after_start_time",
                        violation_error_message="End_time needs to be after start_time",
                    )
                ],
            },
        ),
    ]
