# Generated by Django 5.2.3 on 2026-01-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("argus_incident", "0001_squashed_incident_20250514"),
        ("argus_plannedmaintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedmaintenancetask",
            name="incidents",
            field=models.ManyToManyField(
                blank=True,
                related_name="planned_maintenance_tasks",
                to="argus_incident.incident",
            ),
        ),
    ]
