# Generated by Django 5.2.9 on 2026-02-20 13:19

import argus.plannedmaintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("argus_incident", "0001_squashed_incident_20250514"),
        ("argus_plannedmaintenance", "0002_incidents_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedmaintenancetask",
            name="incidents",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=argus.plannedmaintenance.models.limit_to_open_incidents,
                related_name="planned_maintenance_tasks",
                to="argus_incident.incident",
            ),
        ),
    ]
