# Generated by Django 3.1.6 on 2021-02-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
