# Generated by Django 5.0.7 on 2024-10-02 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_preferences(apps, schema_editor):
    User = apps.get_model("argus_auth", "User")
    Preferences = apps.get_model("argus_auth", "Preferences")
    for user in User.objects.all():
        Preferences.objects.get_or_create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ("argus_auth", "0003_delete_phonenumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preferences",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preferences", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.RunPython(create_preferences, migrations.RunPython.noop),
    ]
