# Generated by Django 3.0.7 on 2020-07-02 17:26

from django.db import migrations
import multiselectfield.db.fields


DAY_TEXT_TO_INDEX = {
    "MO": 1,
    "TU": 2,
    "WE": 3,
    "TH": 4,
    "FR": 5,
    "SA": 6,
    "SU": 7,
}


def convert_from_text_to_index(apps, schema_editor):
    TimeInterval = apps.get_model("argus_notificationprofile", "timeinterval")
    for interval in TimeInterval.objects.all():
        interval.day = DAY_TEXT_TO_INDEX[interval.day]
        interval.save()


class Migration(migrations.Migration):

    dependencies = [
        ('argus_notificationprofile', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_from_text_to_index, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='timeinterval',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=13),
        ),
        migrations.RenameField(
            model_name='timeinterval',
            old_name='day',
            new_name='days',
        ),
    ]
