# Generated by Django 5.2.7 on 2026-01-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_notificationprofile', '0001_squashed_notificationprofile_20250512'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
