# Generated by Django 3.1.6 on 2021-03-03 13:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argus_notificationprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
