# Generated by Django 3.0.7 on 2020-07-03 07:29

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('argus_notificationprofile', '0002_timeinterval_multi_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeInterval',
            new_name='TimeRecurrence',
        ),
        migrations.AlterField(
            model_name='timerecurrence',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_recurrences', to='argus_notificationprofile.Timeslot'),
        ),
    ]
