# Generated by Django 5.2.7 on 2026-02-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_notificationprofile', '0002_filter_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationconfig',
            name='managed',
            field=models.BooleanField(null=True),
        ),
    ]
