# Generated by Django 5.2.7 on 2026-02-19 08:03

from django.db import migrations


def convert_synced_to_managed(apps, schema_editor):
    DestinationConfig = apps.get_model('argus_notificationprofile', 'DestinationConfig')
    for dc in DestinationConfig.objects.filter(media="email"):
        dc.managed = dc.settings.get("synced", False)
        dc.settings.pop("synced", None)
        dc.save()


def convert_managed_to_synced(apps, schema_editor):
    DestinationConfig = apps.get_model('argus_notificationprofile', 'DestinationConfig')
    for dc in DestinationConfig.objects.filter(media="email"):
        dc.settings["synced"] = dc.managed
        dc.managed = None
        dc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('argus_notificationprofile', '0003_destinationconfig_managed'),
    ]

    operations = [
        migrations.RunPython(convert_synced_to_managed, convert_managed_to_synced),
    ]
