# Generated by Django 3.0.8 on 2020-08-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argus_auth', '0002_phonenumber'),
        ('argus_notificationprofile', '0003_rename_timeinterval_to_timerecurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationprofile',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='argus_auth.PhoneNumber'),
        ),
    ]
