# Generated by Django 3.2.6 on 2022-01-13 12:44

from django.db import migrations, models
from django.utils.text import slugify


def create_default_notification_media(apps, schema_editor):
    NotificationMedia = apps.get_model("argus_notificationprofile", "NotificationMedia")
    for media_name in ["Email", "SMS"]:
        NotificationMedia.objects.get_or_create(slug=slugify(media_name), name=media_name)


def map_media_v1_to_media(media_v1):
    if media_v1 == "EM":
        return ["email"]
    if media_v1 == "SM":
        return ["sms"]
    if media_v1 == "SM,EM" or media_v1 == "EM,SM":
        return ["sms", "email"]
    raise ValueError("Value of media_v1: " + media_v1 + " is not supported in v1 of the API.")


def map_media_to_media_v1(media_list):
    media_v1 = []
    for media in media_list:
        if media in ("sms", "email"):
            media_v1.append(media[:2].upper())
    return ",".join(media_v1)


def copy_media_v1_data_to_media(apps, schema_editor):
    NotificationProfile = apps.get_model("argus_notificationprofile", "NotificationProfile")
    for notification_profile in NotificationProfile.objects.all():
        notification_profile.media = map_media_v1_to_media(notification_profile.media_v1)
        notification_profile.save()


def copy_media_data_to_media_v1(apps, schema_editor):
    NotificationProfile = apps.get_model("argus_notificationprofile", "NotificationProfile")
    for notification_profile in NotificationProfile.objects.all():
        media_v1 = map_media_to_media_v1(notification_profile.media)
        if media_v1:
            notification_profile.media_v1 = media_v1
            notification_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("argus_notificationprofile", "0004_copy_notificationprofile_media_to_media_v1"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationMedia",
            fields=[
                ("slug", models.SlugField(blank=True, max_length=20, primary_key=True)),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="notificationprofile",
            name="media",
        ),
        migrations.AddField(
            model_name="notificationprofile",
            name="media",
            field=models.ManyToManyField(
                blank=True, related_name="notification_profiles", to="argus_notificationprofile.NotificationMedia"
            ),
        ),
        migrations.RunPython(create_default_notification_media),
        migrations.RunPython(copy_media_v1_data_to_media, copy_media_data_to_media_v1),
    ]
