# Generated by Django 3.0.7 on 2020-08-20 01:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('argus_notificationprofile', '0004_notificationprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationprofile',
            name='media',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('EM', 'Email'), ('SM', 'SMS'), ('SL', 'Slack')], default=['EM'], max_length=8),
        ),
    ]
