# Generated by Django 5.2.11 on 2026-08-12 14:50

from django.db import migrations



def remove_synced(apps, schema_editor):
    DestinationConfig = apps.get_model('argus_notificationprofile', 'DestinationConfig')
    for dc in DestinationConfig.objects.filter(media="email"):
        dc.settings.pop("synced", None)
        dc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('argus_notificationprofile', '0004_move_synced_to_managed'),
    ]

    operations = [
        migrations.RunPython(remove_synced, migrations.RunPython.noop),
    ]
