# Generated by Django 5.2.13 on 2026-04-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argus_notificationprofile', '0004_move_synced_to_managed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSeenVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('seen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
