# Generated by Django 3.2.6 on 2022-06-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("argus_notificationprofile", "0005_destinationconfig_media"),
    ]

    # Change related name from notification_profile to notification_profiles
    operations = [
        migrations.AlterField(
            model_name="notificationprofile",
            name="destinations",
            field=models.ManyToManyField(
                blank=True, related_name="notification_profiles", to="argus_notificationprofile.DestinationConfig"
            ),
        ),
    ]
