# Generated by Django 3.2.6 on 2022-02-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("argus_notificationprofile", "0007_copy_phone_number_from_destinations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationprofile",
            name="media",
        ),
        migrations.RemoveField(
            model_name="notificationprofile",
            name="media_v1",
        ),
        migrations.RemoveField(
            model_name="notificationprofile",
            name="phone_number",
        ),
    ]
