# Generated by Django 4.1.7 on 2023-04-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("argus_notificationprofile", "0010_notificationprofile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="installed",
            field=models.BooleanField(default=True),
        ),
    ]
