# Generated by Django 4.2.11 on 2024-04-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("argus_notificationprofile", "0001_squashed_0015_remove_days_alter_days_array"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="slug",
            field=models.SlugField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
