# Generated by Django 3.0.7 on 2020-06-24 14:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('alert_id', models.TextField(verbose_name='alert ID')),
                ('details_url', models.TextField(blank=True, validators=[django.core.validators.URLValidator], verbose_name='details URL')),
                ('description', models.TextField(blank=True)),
                ('ticket_url', models.TextField(blank=True, help_text='URL to existing ticket in a ticketing system.', validators=[django.core.validators.URLValidator], verbose_name='ticket URL')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlertRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertSourceType',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParentObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('parentobject_id', models.TextField(verbose_name='parent object ID')),
                ('url', models.TextField(blank=True, validators=[django.core.validators.URLValidator], verbose_name='URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActiveAlert',
            fields=[
                ('alert', models.OneToOneField(help_text="Whether the alert's problem has been resolved.", on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='active_state', serialize=False, to='argus_alert.Alert')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('object_id', models.TextField(blank=True, verbose_name='object ID')),
                ('url', models.TextField(validators=[django.core.validators.URLValidator], verbose_name='URL')),
                ('alert_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_set', to='argus_alert.AlertSource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='argus_alert.ObjectType')),
            ],
        ),
        migrations.AddField(
            model_name='alertsource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='argus_alert.AlertSourceType'),
        ),
        migrations.CreateModel(
            name='AlertRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('alert1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='argus_alert.Alert')),
                ('alert2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='argus_alert.Alert')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_relations', to='argus_alert.AlertRelationType')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='object',
            field=models.ForeignKey(help_text='The most specific object that the alert was about.', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='argus_alert.Object'),
        ),
        migrations.AddField(
            model_name='alert',
            name='parent_object',
            field=models.ForeignKey(blank=True, help_text='An object that the above `object` is possibly a part of.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='argus_alert.ParentObject'),
        ),
        migrations.AddField(
            model_name='alert',
            name='problem_type',
            field=models.ForeignKey(help_text='The type of problem that the alert is informing about.', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='argus_alert.ProblemType'),
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.ForeignKey(help_text='The network management system that the alert came from.', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='argus_alert.AlertSource'),
        ),
        migrations.AddConstraint(
            model_name='object',
            constraint=models.UniqueConstraint(fields=('object_id', 'alert_source'), name='object_unique_object_id_per_alert_source'),
        ),
        migrations.AddConstraint(
            model_name='object',
            constraint=models.UniqueConstraint(fields=('name', 'type', 'alert_source'), name='object_unique_name_and_type_per_alert_source'),
        ),
        migrations.AddConstraint(
            model_name='alertsource',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='alertsource_unique_name_per_type'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('alert_id', 'source'), name='alert_unique_alert_id_per_source'),
        ),
    ]
