# Generated by Django 3.0.7 on 2020-06-25 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_users_for_alert_sources(apps, schema_editor):
    AlertSource = apps.get_model("argus_alert", "AlertSource")
    User = apps.get_model("argus_auth", "User")
    for alert_source in AlertSource.objects.all():
        if not alert_source.user:
            # This username format was arbitrarily chosen
            user, _created = User.objects.get_or_create(username=f"{alert_source.type.name}.{alert_source.name}.no".lower())
            alert_source.user = user
            alert_source.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('argus_alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsource',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_source', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_users_for_alert_sources, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='alertsource',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_source', to=settings.AUTH_USER_MODEL),
        ),
    ]
