# Generated by Django 2.2.13 on 2020-06-18 10:47

from django.db import migrations, models
import django.db.models.deletion


def set_charfield_to_foreignkey(apps, schema_editor):
    AlertSource = apps.get_model("aas_alert", "AlertSource")
    AlertSourceType = apps.get_model("aas_alert", "AlertSourceType")
    for alert_source in AlertSource.objects.all():
        if alert_source.type == "NAV":
            alert_source.type = AlertSourceType.objects.get_or_create(name="NAV")
        elif alert_source.type == "Zabbix":
            alert_source.type = AlertSourceType.objects.get_or_create(name="Zabbix")


class Migration(migrations.Migration):

    dependencies = [
        ('aas_alert', '0003_change_charfields_to_textfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSourceType',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(set_charfield_to_foreignkey, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='alertsource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='aas_alert.AlertSourceType'),
        ),
    ]
