# Generated by Django 2.2.5 on 2019-10-23 00:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notificationprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationprofile',
            name='media',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('EM', 'Email'), ('SM', 'SMS'), ('SL', 'Slack')], default='EM', max_length=8),
        ),
    ]
