# Generated by Django 2.2.5 on 2019-11-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationprofile', '0002_notificationprofile_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationProfile',
        ),
    ]
