# Generated by Django 2.2.5 on 2019-10-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationprofile', '0002_notificationprofile_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('filter', models.TextField()),
            ],
        ),
    ]
