# Generated by Django 2.2.5 on 2019-11-01 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificationprofile', '0002_notificationprofile_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationprofile',
            name='interval_start',
        ),
        migrations.RemoveField(
            model_name='notificationprofile',
            name='interval_stop',
        ),
        migrations.RemoveField(
            model_name='notificationprofile',
            name='name',
        ),
        migrations.CreateModel(
            name='TimeSlotGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='notificationprofile.TimeSlotGroup')),
            ],
        ),
        migrations.AddField(
            model_name='notificationprofile',
            name='time_slot_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification_profiles', to='notificationprofile.TimeSlotGroup'),
            preserve_default=False,
        ),
    ]
