# Generated by Django 2.2.5 on 2019-11-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationprofile', '0003_auto_20191101_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='group',
        ),
    ]
