# Generated by Django 2.2.5 on 2019-10-29 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificationprofile', '0003_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
