# Generated by Django 2.2.5 on 2019-11-12 08:55
from datetime import time

from django.db import migrations

from aas.site.notificationprofile import models as notification_models


def create_default_timeslotgroup_for_users(apps, schema_editor):
    User = apps.get_model('aas_auth', 'User')
    TimeSlotGroup = apps.get_model('notificationprofile', 'TimeSlotGroup')
    TimeSlot = apps.get_model('notificationprofile', 'TimeSlot')

    time_slot_group_name = "Immediately"
    for user in User.objects.all():
        if not user.time_slot_groups.filter(name__iexact=time_slot_group_name).exists():
            time_slot_group = TimeSlotGroup.objects.create(user=user, name=time_slot_group_name)
            time_slot_start, time_slot_end = notification_models.TimeSlot.DAY_START, notification_models.TimeSlot.DAY_END
            for day, _day_name in notification_models.TimeSlot.DAY_CHOICES:
                TimeSlot.objects.create(group=time_slot_group, day=day, start=time_slot_start, end=time_slot_end)


class Migration(migrations.Migration):

    dependencies = [
        ('notificationprofile', '0004_filter_notificationprofile_timeslot_timeslotgroup'),
    ]

    operations = [
        migrations.RunPython(create_default_timeslotgroup_for_users, migrations.RunPython.noop),
    ]
