# Generated by Django 2.2.5 on 2019-11-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationprofile', '0004_remove_timeslot_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationprofile',
            name='time_slot_group',
        ),
    ]
