# Generated by Django 2.2.5 on 2019-11-19 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificationprofile', '0005_default_immediate_timeslotgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSlot',
            new_name='TimeInterval',
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_intervals', to='notificationprofile.TimeSlotGroup'),
        ),
    ]
