# Generated by Django 2.2.5 on 2019-11-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationprofile', '0006_auto_20191101_1210'),
        ('notificationprofile', '0004_filter_user'),
    ]

    operations = [
    ]
