# Generated by Django 2.2.5 on 2019-11-19 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('notificationprofile', '0006_rename_timeslot_to_timeinterval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSlotGroup',
            new_name='TimeSlot',
        ),
        migrations.RenameField(
            model_name='notificationprofile',
            old_name='time_slot_group',
            new_name='time_slot',
        ),
        migrations.RenameField(
            model_name='timeinterval',
            old_name='group',
            new_name='time_slot',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
