# Generated by Django 2.2.5 on 2019-11-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationprofile', '0007_merge_20191101_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationprofile',
            name='filters',
            field=models.ManyToManyField(related_name='notification_profiles', to='notificationprofile.Filter'),
        ),
        migrations.RemoveField(
            model_name='notificationprofile',
            name='group',
        ),
        migrations.AddField(
            model_name='notificationprofile',
            name='group',
            field=models.ManyToManyField(related_name='notification_profiles', to='notificationprofile.TimeSlotGroup'),
        ),
    ]
