# Generated by Django 2.2.5 on 2019-11-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationprofile', '0008_auto_20191101_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationprofile',
            name='filters',
        ),
        migrations.AddField(
            model_name='timeslotgroup',
            name='filters',
            field=models.ManyToManyField(related_name='notification_profiles', to='notificationprofile.Filter'),
        ),
    ]
