# Generated by Django 5.2.13 on 2026-08-26 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioncheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyPIVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.DeleteModel(
            name='LastSeenVersion',
        ),
    ]
