# Generated by Django 2.2.13 on 2020-06-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aas_alert', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkSystem',
            new_name='AlertSource',
        ),
        migrations.RemoveConstraint(
            model_name='alertsource',
            name='networksystem_unique_name_per_type',
        ),
        migrations.RemoveConstraint(
            model_name='object',
            name='object_unique_object_id_per_network_system',
        ),
        migrations.RemoveConstraint(
            model_name='object',
            name='object_unique_name_and_type_per_network_system',
        ),
        migrations.AlterField(
            model_name='object',
            name='network_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_set', to='aas_alert.AlertSource'),
        ),
        migrations.RenameField(
            model_name='object',
            old_name='network_system',
            new_name='alert_source',
        ),
        migrations.AddConstraint(
            model_name='alertsource',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='alertsource_unique_name_per_type'),
        ),
        migrations.AddConstraint(
            model_name='object',
            constraint=models.UniqueConstraint(fields=('object_id', 'alert_source'), name='object_unique_object_id_per_alert_source'),
        ),
        migrations.AddConstraint(
            model_name='object',
            constraint=models.UniqueConstraint(fields=('name', 'type', 'alert_source'), name='object_unique_name_and_type_per_alert_source'),
        ),
    ]
